/**
 * Manual API layer for the unified events API.
 *
 * Types are imported from `./schema` (generated by openapi-typescript from the
 * server's OpenAPI spec). This module re-exports them under friendly names and
 * wraps each endpoint in a fetch + React Query hook.
 */
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import type { UseQueryOptions, UseMutationOptions } from "@tanstack/react-query";

import type { components } from "./schema";

// --- Types (re-exported from generated schema) ---

export type EventSummary = components["schemas"]["EventSummary"];
export type EventDetail = components["schemas"]["EventDetail"];
export type EventListResponse = components["schemas"]["EventListResponse"];
export type EventIdsResponse = components["schemas"]["EventIdsResponse"];
export type EventStatsResponse = components["schemas"]["EventStatsResponse"];
export type HttpEventData = components["schemas"]["HttpEventData"];
export type HttpIncomingEventData = components["schemas"]["HttpIncomingEventData"];
export type LogEventData = components["schemas"]["LogEventData"];
export type ExceptionEventData = components["schemas"]["ExceptionEventData"];
export type ExceptionFrame = components["schemas"]["ExceptionFrame"];
export type TestEventData = components["schemas"]["TestEventData"];
export type TestFailure = components["schemas"]["TestFailure"];
export type TestStatus = TestEventData["status"];
export type MetaResponse = components["schemas"]["MetaResponse"];
export type EventType = EventSummary["event_type"];

export interface ListEventsParams {
  event_type?: string;
  host?: string;
  method?: string;
  status?: number;
  search?: string;
  app?: string;
  session?: string;
  include_ancestors?: boolean;
  after_seq?: number;
  before_seq?: number;
  limit?: number;
}

export interface EventIdsParams {
  event_type?: string;
  host?: string;
  method?: string;
  status?: number;
  search?: string;
  app?: string;
  session?: string;
}

// --- Fetch functions ---

async function fetchJson<T>(url: string, init?: RequestInit): Promise<T> {
  const res = await fetch(url, init);
  if (!res.ok) throw new Error(`${res.status} ${res.statusText}`);
  if ([204, 205, 304].includes(res.status)) return {} as T;
  return res.json();
}

function buildUrl(
  path: string,
  params?: Record<string, string | number | boolean | undefined>,
): string {
  const url = new URL(path, window.location.origin);
  if (params) {
    for (const [k, v] of Object.entries(params)) {
      if (v !== undefined) url.searchParams.set(k, String(v));
    }
  }
  return url.toString();
}

export async function listEvents(params?: ListEventsParams): Promise<EventListResponse> {
  return fetchJson(
    buildUrl("/api/events", params as Record<string, string | number | boolean | undefined>),
  );
}

export async function listEventIds(params?: EventIdsParams): Promise<EventIdsResponse> {
  return fetchJson(
    buildUrl("/api/events/ids", params as Record<string, string | number | undefined>),
  );
}

export async function getEvent(id: string): Promise<EventDetail> {
  return fetchJson(`/api/events/${id}`);
}

export async function getMeta(): Promise<MetaResponse> {
  return fetchJson("/api/meta");
}

export async function clearEvents(): Promise<void> {
  await fetch("/api/events", { method: "DELETE" });
}

// --- Query keys ---

export const eventKeys = {
  all: ["/api/events"] as const,
  store: (session?: string) => ["/api/events", "store", session ?? null] as const,
  storeRoot: ["/api/events", "store"] as const,
  ids: (params: EventIdsParams) => ["/api/events/ids", params] as const,
  search: (params: ListEventsParams) => ["/api/events", "search", params] as const,
  detail: (id: string) => ["/api/events", id] as const,
  meta: ["/api/meta"] as const,
};

// --- Event store ---

/**
 * Every event the browser has loaded for one session, newest first.
 *
 * A run is the natural working set, and it fits in memory (~8 MB at 10,000
 * events), so the store holds it unfiltered and every filter but `search` runs
 * locally. `maxSeq` is the cursor: the largest `seq` actually held, never the
 * server's `max_seq`, so a delta truncated by the page limit cannot open a gap.
 */
export interface EventStore {
  epoch: string;
  maxSeq: number;
  events: EventSummary[];
}

const STORE_PAGE_LIMIT = 10_000;
// A guard against an unbounded catch-up loop, not an expected ceiling: each
// pass advances the cursor by up to STORE_PAGE_LIMIT events.
const MAX_DELTA_PAGES = 50;

function sessionParam(session?: string): { session?: string } {
  return session !== undefined ? { session } : {};
}

function largestSeq(events: EventSummary[]): number {
  return events.reduce((max, event) => Math.max(max, event.seq), 0);
}

async function fetchWholeStore(session?: string): Promise<EventStore> {
  const page = await listEvents({ ...sessionParam(session), limit: STORE_PAGE_LIMIT });
  return { epoch: page.epoch, maxSeq: largestSeq(page.events), events: page.events };
}

// --- React Query hooks ---

export function useEventStore(session?: string, options?: Partial<UseQueryOptions<EventStore>>) {
  const queryClient = useQueryClient();
  return useQuery<EventStore>({
    queryKey: eventKeys.store(session),
    queryFn: async () => {
      const previous = queryClient.getQueryData<EventStore>(eventKeys.store(session));
      if (!previous) return fetchWholeStore(session);

      let store = previous;
      for (let page = 0; page < MAX_DELTA_PAGES; page++) {
        const delta = await listEvents({
          ...sessionParam(session),
          after_seq: store.maxSeq,
          limit: STORE_PAGE_LIMIT,
        });
        // The server dropped rows out from under us; nothing held is trustworthy.
        if (delta.epoch !== store.epoch) return fetchWholeStore(session);
        // A cursor above the server's own maximum is impossible unless rows were
        // removed or renumbered out of band — by another process, a VACUUM, or a
        // manual delete — none of which bump the epoch. Resync rather than sit on
        // a cursor that can never advance again.
        if (delta.max_seq < store.maxSeq) return fetchWholeStore(session);
        // Returning the same reference is the point of the whole design: it
        // stops the hierarchy projection rebuilding on every idle poll.
        if (delta.events.length === 0) return store;

        const pageMaxSeq = largestSeq(delta.events);
        store = {
          epoch: delta.epoch,
          maxSeq: pageMaxSeq,
          events: [...delta.events, ...store.events],
        };
        if (pageMaxSeq >= delta.max_seq) break;
      }
      return store;
    },
    refetchInterval: 3_000,
    ...options,
  });
}

export function useEventIds(
  params: EventIdsParams,
  options?: Partial<UseQueryOptions<EventIdsResponse>>,
) {
  return useQuery({
    queryKey: eventKeys.ids(params),
    queryFn: () => listEventIds(params),
    ...options,
  });
}

/**
 * Fetch search matches directly, for the case where the store cannot answer.
 *
 * `include_ancestors` is on because these rows bypass the store, so nothing
 * else will supply the operations they ran inside.
 */
export function useSearchEvents(
  params: EventIdsParams,
  options?: Partial<UseQueryOptions<EventListResponse>>,
) {
  const query = { ...params, include_ancestors: true, limit: STORE_PAGE_LIMIT };
  return useQuery({
    queryKey: eventKeys.search(query),
    queryFn: () => listEvents(query),
    ...options,
  });
}

export function useGetEvent(id: string, options?: Partial<UseQueryOptions<EventDetail>>) {
  return useQuery({
    queryKey: eventKeys.detail(id),
    queryFn: () => getEvent(id),
    enabled: !!id,
    ...options,
  });
}

export function useGetMeta(options?: Partial<UseQueryOptions<MetaResponse>>) {
  return useQuery({
    queryKey: eventKeys.meta,
    queryFn: getMeta,
    ...options,
  });
}

export function useClearEvents(options?: UseMutationOptions<void, Error, void>) {
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: clearEvents,
    onSuccess: (...args) => {
      // Drop the store rather than invalidate it: its cursor now points past
      // the end of an empty table, and a refetch would carry stale rows.
      queryClient.removeQueries({ queryKey: eventKeys.storeRoot });
      queryClient.invalidateQueries({ queryKey: eventKeys.all });
      queryClient.invalidateQueries({ queryKey: eventKeys.meta });
      options?.onSuccess?.(...args);
    },
    ...options,
  });
}
