/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/api/capture/http": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Capture Http Api */
    post: operations["capture_http_api_api_capture_http_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/capture/http_incoming": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Capture Http Incoming Api */
    post: operations["capture_http_incoming_api_api_capture_http_incoming_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/capture/log": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Capture Log Api */
    post: operations["capture_log_api_api_capture_log_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/capture/exception": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Capture Exception Api */
    post: operations["capture_exception_api_api_capture_exception_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/capture/test": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Capture Test Api */
    post: operations["capture_test_api_api_capture_test_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/capture": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Deprecated: use /api/capture/http
     * @deprecated
     * @description Deprecated HTTP capture endpoint.
     *
     *     Kept for backwards compatibility with legacy pre-TraceLoom client wheels,
     *     which only ever posted HTTP captures here. New clients should use the
     *     typed endpoints `/api/capture/http`, `/api/capture/log`,
     *     `/api/capture/exception`.
     */
    post: operations["capture_legacy_api_api_capture_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/events": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Events Api */
    get: operations["list_events_api_api_events_get"];
    put?: never;
    post?: never;
    /** Clear Events Api */
    delete: operations["clear_events_api_api_events_delete"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/events/ids": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Event Ids Api */
    get: operations["list_event_ids_api_api_events_ids_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/events/stats": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Stats Api */
    get: operations["get_stats_api_api_events_stats_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/events/{event_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Event Api */
    get: operations["get_event_api_api_events__event_id__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/meta": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Meta Api */
    get: operations["get_meta_api_api_meta_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /** CaptureResponse */
    CaptureResponse: {
      /** Status */
      status: string;
    };
    /** EventDetail */
    EventDetail: {
      /** Id */
      id: string;
      /** Seq */
      seq: number;
      /**
       * Timestamp
       * Format: date-time
       */
      timestamp: string;
      /**
       * Event Type
       * @enum {string}
       */
      event_type: "http" | "http_incoming" | "log" | "exception" | "test";
      /** Summary */
      summary: string;
      /**
       * App
       * @default
       */
      app: string;
      /**
       * Session
       * @default
       */
      session: string;
      /** Host */
      host?: string | null;
      /** Method */
      method?: string | null;
      /** Status Code */
      status_code?: number | null;
      hierarchy?: components["schemas"]["EventHierarchy-Output"] | null;
      /** Data */
      data:
        | components["schemas"]["HttpEventData"]
        | components["schemas"]["HttpIncomingEventData"]
        | components["schemas"]["LogEventData"]
        | components["schemas"]["ExceptionEventData"]
        | components["schemas"]["TestEventData"];
    };
    /**
     * EventHierarchy
     * @description Runtime correlation and grouping context captured with one event.
     */
    "EventHierarchy-Input": {
      runtime?: components["schemas"]["RuntimeCorrelation"] | null;
      /**
       * Group Memberships
       * @default []
       */
      group_memberships: (
        | components["schemas"]["PytestGroupMembership"]
        | components["schemas"]["HttpRequestGroupMembership"]
      )[];
    };
    /**
     * EventHierarchy
     * @description Runtime correlation and grouping context captured with one event.
     */
    "EventHierarchy-Output": {
      runtime?: components["schemas"]["RuntimeCorrelation"] | null;
      /**
       * Group Memberships
       * @default []
       */
      group_memberships: (
        | components["schemas"]["PytestGroupMembership"]
        | components["schemas"]["HttpRequestGroupMembership"]
      )[];
    };
    /**
     * EventIdsResponse
     * @description Matching event IDs only — the payload for server-side body search.
     */
    EventIdsResponse: {
      /** Epoch */
      epoch: string;
      /** Ids */
      ids: string[];
    };
    /**
     * EventListResponse
     * @description A page of events plus the cursor state needed to follow the tail.
     *
     *     ``epoch`` changes whenever stored rows are removed wholesale (clear-all,
     *     retention prune, server restart). A client whose cached ``epoch`` no longer
     *     matches must drop its store and resync.
     *
     *     ``max_seq`` is the largest ``seq`` in the table matching the non-cursor
     *     filters — not merely the largest on this page. A delta whose page tops out
     *     below ``max_seq`` was truncated by ``limit``; poll again immediately.
     */
    EventListResponse: {
      /** Epoch */
      epoch: string;
      /** Max Seq */
      max_seq: number;
      /** Events */
      events: components["schemas"]["EventSummary"][];
    };
    /**
     * EventStatsResponse
     * @description Aggregate counts for a filter, so consumers need not download the rows.
     */
    EventStatsResponse: {
      /** Epoch */
      epoch: string;
      /** Max Seq */
      max_seq: number;
      /** Total */
      total: number;
      /** By Event Type */
      by_event_type: {
        [key: string]: number;
      };
      /** By Test Status */
      by_test_status: {
        [key: string]: number;
      };
      /** By Status Class */
      by_status_class: {
        [key: string]: number;
      };
    };
    /**
     * EventSummary
     * @description One row of the event list.
     *
     *     ``seq`` is the server's insertion-order cursor (SQLite's ``rowid``). It is
     *     the only ordering that survives a fast run: ``timestamp`` has one-second
     *     resolution on the client and the client's background worker does not
     *     preserve order anyway.
     *
     *     ``host``, ``method`` and ``status_code`` are carried so consumers can filter
     *     a loaded store without going back to the server.
     */
    EventSummary: {
      /** Id */
      id: string;
      /** Seq */
      seq: number;
      /**
       * Timestamp
       * Format: date-time
       */
      timestamp: string;
      /**
       * Event Type
       * @enum {string}
       */
      event_type: "http" | "http_incoming" | "log" | "exception" | "test";
      /** Summary */
      summary: string;
      /**
       * App
       * @default
       */
      app: string;
      /**
       * Session
       * @default
       */
      session: string;
      /** Host */
      host?: string | null;
      /** Method */
      method?: string | null;
      /** Status Code */
      status_code?: number | null;
      hierarchy?: components["schemas"]["EventHierarchy-Output"] | null;
    };
    /** ExceptionCapturePayload */
    ExceptionCapturePayload: {
      /** Id */
      id?: string | null;
      /** Timestamp */
      timestamp?: string | null;
      /**
       * App
       * @default
       */
      app: string;
      /**
       * Session
       * @default
       */
      session: string;
      hierarchy?: components["schemas"]["EventHierarchy-Input"] | null;
      data: components["schemas"]["ExceptionData"];
    };
    /** ExceptionData */
    ExceptionData: {
      /** Exc Type */
      exc_type: string;
      /**
       * Exc Value
       * @default
       */
      exc_value: string;
      /** Exc Module */
      exc_module?: string | null;
      /**
       * Traceback Text
       * @default
       */
      traceback_text: string;
      /**
       * Frames
       * @default []
       */
      frames: components["schemas"]["ExceptionFrame"][];
    } & {
      [key: string]: unknown;
    };
    /** ExceptionEventData */
    ExceptionEventData: {
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      event_type: "exception";
      /**
       * App
       * @default
       */
      app: string;
      /**
       * Session
       * @default
       */
      session: string;
      /** Exc Type */
      exc_type: string;
      /**
       * Exc Value
       * @default
       */
      exc_value: string;
      /** Exc Module */
      exc_module?: string | null;
      /**
       * Traceback Text
       * @default
       */
      traceback_text: string;
      /**
       * Frames
       * @default []
       */
      frames: components["schemas"]["ExceptionFrame"][];
    };
    /** ExceptionFrame */
    ExceptionFrame: {
      /** Filename */
      filename: string;
      /** Lineno */
      lineno?: number | null;
      /** Function */
      function?: string | null;
      /** Context Line */
      context_line?: string | null;
      /**
       * Pre Context
       * @default []
       */
      pre_context: string[];
      /**
       * Post Context
       * @default []
       */
      post_context: string[];
    };
    /**
     * GroupReference
     * @description Stable group identity and its display label.
     */
    GroupReference: {
      /** Id */
      id: string;
      /** Label */
      label: string;
    };
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components["schemas"]["ValidationError"][];
    };
    /** HttpCapturePayload */
    HttpCapturePayload: {
      /** Id */
      id?: string | null;
      /** Timestamp */
      timestamp?: string | null;
      /**
       * App
       * @default
       */
      app: string;
      /**
       * Session
       * @default
       */
      session: string;
      hierarchy?: components["schemas"]["EventHierarchy-Input"] | null;
      /**
       * Duration Ms
       * @default 0
       */
      duration_ms: number;
      request: components["schemas"]["HttpRequestData"];
      response?: components["schemas"]["HttpResponseData"] | null;
      error?: components["schemas"]["HttpOperationError"] | null;
      meta?: components["schemas"]["HttpMeta"];
    };
    /**
     * HttpEventData
     * @description HTTP capture as stored and served. Flat by convention.
     */
    HttpEventData: {
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      event_type: "http";
      /**
       * App
       * @default
       */
      app: string;
      /**
       * Session
       * @default
       */
      session: string;
      /** Duration Ms */
      duration_ms: number;
      /** Method */
      method: string;
      /** Url */
      url: string;
      /** Host */
      host: string;
      /** Request Headers */
      request_headers: {
        [key: string]: string;
      };
      /** Request Body */
      request_body?: string | null;
      /**
       * Request Body Size
       * @default 0
       */
      request_body_size: number;
      /** Status Code */
      status_code?: number | null;
      /** Response Headers */
      response_headers?: {
        [key: string]: string;
      };
      /** Response Body */
      response_body?: string | null;
      /**
       * Response Body Size
       * @default 0
       */
      response_body_size: number;
      error?: components["schemas"]["HttpOperationError"] | null;
      /**
       * Library
       * @default unknown
       */
      library: string;
      /**
       * Python Version
       * @default
       */
      python_version: string;
      /**
       * Traceloom Version
       * @default
       */
      traceloom_version: string;
    };
    /** HttpIncomingCapturePayload */
    HttpIncomingCapturePayload: {
      /** Id */
      id?: string | null;
      /** Timestamp */
      timestamp?: string | null;
      /**
       * App
       * @default
       */
      app: string;
      /**
       * Session
       * @default
       */
      session: string;
      hierarchy?: components["schemas"]["EventHierarchy-Input"] | null;
      /**
       * Duration Ms
       * @default 0
       */
      duration_ms: number;
      request: components["schemas"]["HttpIncomingRequestData"];
      response: components["schemas"]["HttpIncomingResponseData"];
      meta?: components["schemas"]["HttpIncomingMeta"];
    };
    /**
     * HttpIncomingEventData
     * @description Incoming HTTP request as stored and served.
     */
    HttpIncomingEventData: {
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      event_type: "http_incoming";
      /**
       * App
       * @default
       */
      app: string;
      /**
       * Session
       * @default
       */
      session: string;
      /** Duration Ms */
      duration_ms: number;
      /** Method */
      method: string;
      /** Path */
      path: string;
      /** Url */
      url: string;
      /** Host */
      host: string;
      /** Route */
      route?: string | null;
      /** Client Ip */
      client_ip?: string | null;
      /** Request Headers */
      request_headers: {
        [key: string]: string;
      };
      /** Request Body */
      request_body?: string | null;
      /**
       * Request Body Size
       * @default 0
       */
      request_body_size: number;
      /** Status Code */
      status_code: number;
      /** Response Headers */
      response_headers: {
        [key: string]: string;
      };
      /** Response Body */
      response_body?: string | null;
      /**
       * Response Body Size
       * @default 0
       */
      response_body_size: number;
      /** Exc Type */
      exc_type?: string | null;
      /** Exc Value */
      exc_value?: string | null;
      /**
       * Framework
       * @default unknown
       */
      framework: string;
      /**
       * Python Version
       * @default
       */
      python_version: string;
      /**
       * Traceloom Version
       * @default
       */
      traceloom_version: string;
    };
    /** HttpIncomingMeta */
    HttpIncomingMeta: {
      /**
       * Framework
       * @default unknown
       */
      framework: string;
      /** Route */
      route?: string | null;
      /** Client Ip */
      client_ip?: string | null;
      /** Exc Type */
      exc_type?: string | null;
      /** Exc Value */
      exc_value?: string | null;
      /**
       * Python Version
       * @default
       */
      python_version: string;
      /**
       * Traceloom Version
       * @default
       */
      traceloom_version: string;
    };
    /** HttpIncomingRequestData */
    HttpIncomingRequestData: {
      /** Method */
      method: string;
      /** Path */
      path: string;
      /** Url */
      url: string;
      /** Headers */
      headers: {
        [key: string]: string;
      };
      /** Body */
      body?: string | null;
      /**
       * Body Size
       * @default 0
       */
      body_size: number;
    };
    /** HttpIncomingResponseData */
    HttpIncomingResponseData: {
      /** Status Code */
      status_code: number;
      /** Headers */
      headers: {
        [key: string]: string;
      };
      /** Body */
      body?: string | null;
      /**
       * Body Size
       * @default 0
       */
      body_size: number;
    };
    /** HttpMeta */
    HttpMeta: {
      /**
       * Library
       * @default unknown
       */
      library: string;
      /**
       * Python Version
       * @default
       */
      python_version: string;
      /**
       * Traceloom Version
       * @default
       */
      traceloom_version: string;
    };
    /**
     * HttpOperationError
     * @description Exception raised by an outgoing HTTP operation.
     */
    HttpOperationError: {
      /** Type */
      type: string;
      /**
       * Message
       * @default
       */
      message: string;
      /** Module */
      module?: string | null;
    };
    /** HttpRequestData */
    HttpRequestData: {
      /** Method */
      method: string;
      /** Url */
      url: string;
      /** Headers */
      headers: {
        [key: string]: string;
      };
      /** Body */
      body?: string | null;
      /**
       * Body Size
       * @default 0
       */
      body_size: number;
    };
    /**
     * HttpRequestGroupMembership
     * @description Position in the outgoing HTTP target hierarchy.
     */
    HttpRequestGroupMembership: {
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      kind: "http_request";
      hostname: components["schemas"]["GroupReference"];
    };
    /** HttpResponseData */
    HttpResponseData: {
      /** Status Code */
      status_code: number;
      /** Headers */
      headers: {
        [key: string]: string;
      };
      /** Body */
      body?: string | null;
      /**
       * Body Size
       * @default 0
       */
      body_size: number;
    };
    /** LogCapturePayload */
    LogCapturePayload: {
      /** Id */
      id?: string | null;
      /** Timestamp */
      timestamp?: string | null;
      /**
       * App
       * @default
       */
      app: string;
      /**
       * Session
       * @default
       */
      session: string;
      hierarchy?: components["schemas"]["EventHierarchy-Input"] | null;
      data: components["schemas"]["LogData"];
    };
    /** LogData */
    LogData: {
      /** Level */
      level: string;
      /** Logger Name */
      logger_name: string;
      /** Message */
      message: string;
      /** Pathname */
      pathname?: string | null;
      /** Lineno */
      lineno?: number | null;
      /** Func Name */
      func_name?: string | null;
      /** Exc Text */
      exc_text?: string | null;
      /** Extra */
      extra?: {
        [key: string]: unknown;
      } | null;
    } & {
      [key: string]: unknown;
    };
    /** LogEventData */
    LogEventData: {
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      event_type: "log";
      /**
       * App
       * @default
       */
      app: string;
      /**
       * Session
       * @default
       */
      session: string;
      /** Level */
      level: string;
      /** Logger Name */
      logger_name: string;
      /** Message */
      message: string;
      /** Pathname */
      pathname?: string | null;
      /** Lineno */
      lineno?: number | null;
      /** Func Name */
      func_name?: string | null;
      /** Exc Text */
      exc_text?: string | null;
      /** Extra */
      extra?: {
        [key: string]: unknown;
      } | null;
    };
    /** MetaResponse */
    MetaResponse: {
      /** Server Version */
      server_version: string;
      /** Hosts */
      hosts: string[];
      /** Methods */
      methods: string[];
      /** Event Types */
      event_types: ("http" | "http_incoming" | "log" | "exception" | "test")[];
      /** Apps */
      apps: string[];
      /** Sessions */
      sessions: string[];
    };
    /**
     * PytestGroupMembership
     * @description Position in pytest's collection hierarchy.
     */
    PytestGroupMembership: {
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      kind: "pytest";
      test_directory?: components["schemas"]["GroupReference"] | null;
      test_file: components["schemas"]["GroupReference"];
      test_class?: components["schemas"]["GroupReference"] | null;
      test_case: components["schemas"]["GroupReference"];
    };
    /**
     * RuntimeCorrelation
     * @description Runtime identity owned or referenced by one captured event.
     */
    RuntimeCorrelation: {
      /** Trace Id */
      trace_id: string;
      /** Span Id */
      span_id: string;
      /** Parent Span Id */
      parent_span_id?: string | null;
      /**
       * Role
       * @enum {string}
       */
      role: "operation" | "annotation";
      /**
       * Origin
       * @default traceloom
       * @enum {string}
       */
      origin: "traceloom" | "otel";
    };
    /** TestCapturePayload */
    TestCapturePayload: {
      /** Id */
      id?: string | null;
      /** Timestamp */
      timestamp?: string | null;
      /**
       * App
       * @default
       */
      app: string;
      /**
       * Session
       * @default
       */
      session: string;
      hierarchy?: components["schemas"]["EventHierarchy-Input"] | null;
      data: components["schemas"]["TestData"];
    };
    /** TestData */
    TestData: {
      /**
       * Framework
       * @default pytest
       */
      framework: string;
      /**
       * Framework Version
       * @default
       */
      framework_version: string;
      /**
       * Python Version
       * @default
       */
      python_version: string;
      /**
       * Traceloom Version
       * @default
       */
      traceloom_version: string;
      /** Run Id */
      run_id: string;
      /**
       * Worker Id
       * @default master
       */
      worker_id: string;
      /** Test Id */
      test_id: string;
      /** Parameter Id */
      parameter_id?: string | null;
      /** Name */
      name: string;
      /** Path */
      path: string;
      /** Line */
      line?: number | null;
      /**
       * Status
       * @enum {string}
       */
      status: "passed" | "failed" | "error" | "skipped" | "xfailed" | "xpassed";
      /** Duration Ms */
      duration_ms: number;
      /**
       * Setup Duration Ms
       * @default 0
       */
      setup_duration_ms: number;
      /**
       * Call Duration Ms
       * @default 0
       */
      call_duration_ms: number;
      /**
       * Teardown Duration Ms
       * @default 0
       */
      teardown_duration_ms: number;
      /**
       * Fixtures
       * @default []
       */
      fixtures: string[];
      /**
       * Failures
       * @default []
       */
      failures: components["schemas"]["TestFailure"][];
    } & {
      [key: string]: unknown;
    };
    /** TestEventData */
    TestEventData: {
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      event_type: "test";
      /**
       * App
       * @default
       */
      app: string;
      /**
       * Session
       * @default
       */
      session: string;
      /**
       * Framework
       * @default pytest
       */
      framework: string;
      /**
       * Framework Version
       * @default
       */
      framework_version: string;
      /**
       * Python Version
       * @default
       */
      python_version: string;
      /**
       * Traceloom Version
       * @default
       */
      traceloom_version: string;
      /** Run Id */
      run_id: string;
      /**
       * Worker Id
       * @default master
       */
      worker_id: string;
      /** Test Id */
      test_id: string;
      /** Parameter Id */
      parameter_id?: string | null;
      /** Name */
      name: string;
      /** Path */
      path: string;
      /** Line */
      line?: number | null;
      /**
       * Status
       * @enum {string}
       */
      status: "passed" | "failed" | "error" | "skipped" | "xfailed" | "xpassed";
      /** Duration Ms */
      duration_ms: number;
      /**
       * Setup Duration Ms
       * @default 0
       */
      setup_duration_ms: number;
      /**
       * Call Duration Ms
       * @default 0
       */
      call_duration_ms: number;
      /**
       * Teardown Duration Ms
       * @default 0
       */
      teardown_duration_ms: number;
      /**
       * Fixtures
       * @default []
       */
      fixtures: string[];
      /**
       * Failures
       * @default []
       */
      failures: components["schemas"]["TestFailure"][];
    };
    /** TestFailure */
    TestFailure: {
      /**
       * Phase
       * @enum {string}
       */
      phase: "setup" | "call" | "teardown";
      /** Exception Type */
      exception_type?: string | null;
      /**
       * Message
       * @default
       */
      message: string;
      /**
       * Traceback Text
       * @default
       */
      traceback_text: string;
    };
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
      /** Input */
      input?: unknown;
      /** Context */
      ctx?: Record<string, never>;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  capture_http_api_api_capture_http_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["HttpCapturePayload"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CaptureResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  capture_http_incoming_api_api_capture_http_incoming_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["HttpIncomingCapturePayload"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CaptureResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  capture_log_api_api_capture_log_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["LogCapturePayload"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CaptureResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  capture_exception_api_api_capture_exception_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ExceptionCapturePayload"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CaptureResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  capture_test_api_api_capture_test_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["TestCapturePayload"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CaptureResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  capture_legacy_api_api_capture_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["HttpCapturePayload"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CaptureResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  list_events_api_api_events_get: {
    parameters: {
      query?: {
        event_type?: string | null;
        host?: string | null;
        method?: string | null;
        status?: number | null;
        search?: string | null;
        app?: string | null;
        session?: string | null;
        include_ancestors?: boolean;
        /** @description Return only events inserted after this seq, oldest first. */
        after_seq?: number | null;
        /** @description Return only events inserted before this seq (backfill). */
        before_seq?: number | null;
        limit?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["EventListResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  clear_events_api_api_events_delete: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  list_event_ids_api_api_events_ids_get: {
    parameters: {
      query?: {
        event_type?: string | null;
        host?: string | null;
        method?: string | null;
        status?: number | null;
        search?: string | null;
        app?: string | null;
        session?: string | null;
        limit?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["EventIdsResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_stats_api_api_events_stats_get: {
    parameters: {
      query?: {
        event_type?: string | null;
        host?: string | null;
        method?: string | null;
        status?: number | null;
        search?: string | null;
        app?: string | null;
        session?: string | null;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["EventStatsResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_event_api_api_events__event_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        event_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["EventDetail"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_meta_api_api_meta_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["MetaResponse"];
        };
      };
    };
  };
}
